<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateArquivoRemessaBoletoDetsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('arquivo_remessa_boleto_dets', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('id_arquivo_boleto');
            $table->string('nome_apresentante', 50)->nullable();
            $table->string('codigo_barra_boleto', 50)->nullable();
            $table->string('linha_digitavel_boleto', 55)->nullable();
            $table->string('nosso_numero_boleto', 200)->nullable();
            $table->string('agencia_codigo_cedente', 20)->nullable();
            $table->string('nome_cedente', 50)->nullable();
            $table->string('nome_sacado', 150)->nullable();
            $table->string('documento_sacado', 255)->nullable();
            $table->string('endereco_sacado', 200)->nullable();
            $table->string('nome_sacador', 150)->nullable();
            $table->string('vencimento_boleto', 10)->nullable();
            $table->string('carteira_boleto', 3)->nullable();
            $table->string('aceite_boleto', 1)->nullable();
            $table->string('especie_pagamento_boleto', 10)->nullable();
            $table->string('numero_documento_boleto', 20)->nullable();
            $table->decimal('valor_principal_titulo', 14, 2)->nullable();
            $table->decimal('valor_custas_emolumento', 14, 2)->nullable();
            $table->decimal('valor_total_boleto', 14, 2)->nullable();
            $table->string('numero_ar', 20)->nullable();
            $table->string('data_apontamento', 10)->nullable();
            $table->string('protocolo', 10)->nullable();
            $table->string('especie_titulo', 3)->nullable();
            $table->string('numero_titulo', 20)->nullable();
            $table->date('data_emissao_titulo')->nullable();
            $table->string('data_vencimento_titulo', 10)->nullable();
            $table->string('nosso_numero_titulo', 20)->nullable();
            $table->string('livro_apontamento', 10)->nullable();
            $table->string('folha_apontamento', 3)->nullable();
            $table->string('ordem_apontamento', 10)->nullable();
            $table->string('sequencial_registro_arquivo', 4)->nullable();
            $table->integer('impresso')->nullable();
            $table->integer('enviaemail')->nullable()->default(0);
            $table->timestamps();
            $table->timestamp('dataprimimpressao')->nullable();
            $table->index('id_arquivo_boleto', 'fk_arquivo_boleto_idx');
            $table->index('protocolo', 'arquivo_remessa_boleto_dets_protocolo_IDX');
            $table->index('vencimento_boleto', 'arquivo_remessa_boleto_dets_vencimento_boleto_IDX');
            $table->index('documento_sacado', 'arquivo_remessa_boleto_dets_documento_sacado_IDX');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('arquivo_remessa_boleto_dets');
    }
}
