<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDevedoresTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('devedores', function (Blueprint $table) {
            $table->increments('id');
            $table->tinyInteger('tipo_doc');
            $table->string('documento', 255);
            $table->string('nome', 255)->nullable();
            $table->string('origem', 100);
            $table->timestamps();
            $table->unique('documento', 'devedores_UN');
            $table->index('documento', 'devedores_documento_IDX');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('devedores');
    }
}
