<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateImagemCredenciamentoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('imagem_credenciamento', function (Blueprint $table) {
            $table->increments('id');
            $table->string('path', 255)->nullable();
            $table->integer('tipo_imagem');
            $table->unsignedInteger('id_user');
            $table->integer('ultima')->nullable()->default(0);
            $table->dateTime('created_at')->nullable();
            $table->dateTime('updated_at')->nullable();
            $table->index('tipo_imagem', 'fk_tipo_imagem_idx');
            $table->index('id_user', 'fk_id_user_idx');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('imagem_credenciamento');
    }
}
