<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDevedorContatoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('devedor_contato', function (Blueprint $table) {
            $table->increments('devedor_contato_id');
            $table->unsignedInteger('devedor_id');
            $table->string('contato', 100);
            $table->integer('tipo_contato');
            $table->string('origem', 100);
            $table->timestamps();
            $table->index('devedor_id', 'devedor_contato_FK');
            $table->index('contato', 'devedor_contato_contato_IDX');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('devedor_contato');
    }
}
