<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateUsersTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('users', function (Blueprint $table) {
            $table->increments('id');
            $table->string('name', 255)->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('email', 255)->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('password', 255)->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('cpf', 255)->nullable();
            $table->string('cep', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('endereco', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('bairro', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('numero', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('complemento', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('telefone', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('celular1', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('celular2', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->text('motivo_descrendenciamento')->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('nomemae', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->integer('creden')->nullable();
            $table->unsignedInteger('cidade_id');
            $table->unsignedInteger('papel_id')->nullable();
            $table->unsignedInteger('cartorio_id')->nullable();
            $table->rememberToken()->charset('utf8')->collation('utf8_unicode_ci');
            $table->tinyInteger('verified')->default(0);
            $table->timestamps();
            $table->softDeletes();
            $table->string('data_nascimento', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('token_notificacao', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('cidade', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->string('creden_image', 255)->nullable()->charset('utf8')->collation('utf8_unicode_ci');
            $table->timestamp('celular_verificado_at')->nullable();
            $table->timestamp('adesao_at')->nullable();
            $table->unique('email', 'users_email_unique');
            $table->index('papel_id', 'users_papel_id_foreign');
            $table->index('cartorio_id', 'users_cartorio_id_foreign');
            $table->index('cidade_id', 'users_cidade_id_foreign');
            $table->index('cpf', 'users_cpf_IDX');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('users');
    }
}
