<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDevedorEnderecoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('devedor_endereco', function (Blueprint $table) {
            $table->increments('devedor_endereco_id');
            $table->unsignedInteger('devedor_id');
            $table->string('tipo_endereco', 45)->comment('Tipos: 1- Via Título; 2 - Via Manual; 3 - Via Sistema Externo');
            $table->string('cep', 45);
            $table->string('endereco', 45);
            $table->string('bairro', 45);
            $table->string('numero', 45);
            $table->string('complemento', 45);
            $table->unsignedInteger('cidade_id');
            $table->unsignedInteger('usuario_id');
            $table->timestamps();
            $table->index('cidade_id', 'devedor_endereco_FK');
            $table->index('devedor_id', 'devedor_endereco_FK_1');
            $table->index('usuario_id', 'devedor_endereco_FK_2');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('devedor_endereco');
    }
}
