<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateEventosInscricaoTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('eventos_inscricao', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255);
            $table->string('cpf', 255);
            $table->string('rg', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('telefone', 255)->nullable();
            $table->string('celular', 255);
            $table->unsignedInteger('cidade_id');
            $table->string('empresa', 255)->nullable();
            $table->string('endereco', 255);
            $table->integer('inscricao')->nullable();
            $table->unsignedInteger('evento_id');
            $table->nullableTimestamps();
            $table->string('comprovante_url', 100)->nullable();
            $table->string('confirmado', 100)->nullable();
            $table->string('comprovante_estudante', 255)->nullable();
            $table->string('credenciado', 100)->nullable();
            $table->string('credenciamento_saida', 100)->nullable();
            $table->string('certificado', 255)->nullable();
            $table->index(['evento_id', 'cidade_id'], 'fk_evento_inscricao_idx');
            $table->index('cidade_id', 'fk_cidade_inscrito_idx');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('eventos_inscricao');
    }
}
