<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateDownloadsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('downloads', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->string('titulo', 255);
            $table->string('slug', 255);
            $table->smallInteger('status')->default(0);
            $table->string('arquivo', 255);
            $table->string('arquivo_url', 255);
            $table->string('conteudo', 255)->nullable();
            $table->timestamps();
            $table->unsignedInteger('categoria_downloadid')->nullable();
            $table->index('user_id', 'downloads_user_id_foreign');
            $table->index('categoria_downloadid', 'down_cat_id_idx');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('downloads');
    }
}
