<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateNotificacaoDevedorTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('notificacao_devedor', function (Blueprint $table) {
            $table->increments('notificacao_devedor_id');
            $table->unsignedInteger('devedor_id');
            $table->unsignedInteger('titulo_id');
            $table->unsignedInteger('devedor_contato_id');
            $table->text('mensagem_enviada');
            $table->text('mensagem_enviada_resp')->nullable();
            $table->text('url_retorno')->nullable();
            $table->string('mensagem_sid', 255)->nullable();
            $table->timestamps();
            $table->index('devedor_id', 'notificacao_devedor_FK');
            $table->index('titulo_id', 'notificacao_devedor_FK_1');
            $table->index('mensagem_sid', 'notificacao_devedor_mensagem_sid_IDX');
            $table->index('devedor_contato_id', 'notificacao_devedor_devedor_contato_id_IDX');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('notificacao_devedor');
    }
}
