<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCartorioResponsavelsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cartorio_responsavels', function (Blueprint $table) {
            $table->unsignedInteger('cartorio_id');
            $table->unsignedInteger('tipo_responsavel_id');
            $table->string('nome', 255);
            $table->string('cpf', 255)->nullable();
            $table->string('rg', 255)->nullable();
            $table->string('endereco', 255)->nullable();
            $table->string('numero', 255)->nullable();
            $table->string('bairro', 255)->nullable();
            $table->string('cep', 255)->nullable();
            $table->string('tel', 255)->nullable();
            $table->string('cel1', 255)->nullable();
            $table->string('cel2', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->timestamps();
            $table->unsignedInteger('cidade_id')->nullable();
            $table->string('complemento', 255)->nullable();
            $table->index('cartorio_id', 'cartorio_responsavels_cartorio_id_foreign');
            $table->index('tipo_responsavel_id', 'cartorio_responsavels_tipo_responsavel_id_foreign');
            $table->index('cidade_id', 'cartorio_responsavels_cidade_id_foreign');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cartorio_responsavels');
    }
}
