<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateTitulosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('titulos', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->unsignedInteger('cartorio_id')->nullable();
            $table->unsignedInteger('devedor_id');
            $table->unsignedInteger('remessa_id')->nullable();
            $table->string('apresentante', 255)->nullable();
            $table->string('protocolo', 255)->nullable();
            $table->string('numero_titulo', 255)->nullable();
            $table->string('nosso_numero', 255)->nullable();
            $table->unsignedInteger('especie_id');
            $table->date('emissao');
            $table->double('valor');
            $table->double('custos');
            $table->double('saldo');
            $table->double('custas');
            $table->unsignedInteger('praca_protesto_id');
            $table->unsignedInteger('tipo_vencimento_id');
            $table->date('vencimento');
            $table->tinyInteger('aceite');
            $table->tinyInteger('fim_falimentar');
            $table->unsignedInteger('endosso_id');
            $table->tinyInteger('cancelado');
            $table->timestamps();
            $table->string('cedente', 255)->nullable();
            $table->index('user_id', 'titulos_user_id_foreign');
            $table->index('cartorio_id', 'titulos_cartorio_id_foreign');
            $table->index('devedor_id', 'titulos_devedor_id_foreign');
            $table->index('endosso_id', 'titulos_endosso_id_foreign');
            $table->index('especie_id', 'titulos_especie_id_foreign');
            $table->index('remessa_id', 'titulos_remessa_id_foreign');
            
            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('titulos');
    }
}
