<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateCartoriosTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('cartorios', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255);
            $table->string('responsavelinfo', 255)->nullable();
            $table->string('cnpj', 255)->nullable();
            $table->string('bairro', 255)->nullable();
            $table->string('endereco', 255)->nullable();
            $table->string('numero', 255)->nullable();
            $table->string('cep', 255)->nullable();
            $table->string('complemento', 255)->nullable();
            $table->string('site', 255)->nullable();
            $table->integer('informatizado')->nullable();
            $table->string('empresainfo', 255)->nullable();
            $table->string('contatoinfo', 255)->nullable();
            $table->unsignedInteger('cidade_id')->nullable();
            $table->string('upload', 255)->nullable();
            $table->tinyInteger('status')->nullable()->default(1);
            $table->timestamps();
            $table->string('latitude', 45)->nullable();
            $table->string('longitude', 45)->nullable();

            $table->charset = 'utf8';
            $table->collation = 'utf8_unicode_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('cartorios');
    }
}
