<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateProtonlineTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('protonline', function (Blueprint $table) {
            $table->increments('id');
            $table->string('nome', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->string('contato', 50);
            $table->string('empresa', 255)->nullable();
            $table->string('mensagem', 255);
            $table->nullableTimestamps();
            $table->string('cnpj', 100)->nullable();
            $table->string('razao', 255)->nullable();
            $table->string('whatsapp', 100)->nullable();
            $table->string('celular', 100)->nullable();
            $table->string('segmento', 100)->nullable();
            $table->string('tipo_protesto', 255)->nullable();
            $table->string('qtd_titulos', 100)->nullable();

            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('protonline');
    }
}
