<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateLegislacoesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('legislacoes', function (Blueprint $table) {
            $table->increments('id');
            $table->string('descricao', 255);
            $table->unsignedInteger('tipo_legislacao_id');
            $table->unsignedInteger('user_id');
            $table->integer('status');
            $table->string('arquivo', 95)->nullable();
            $table->string('arquivo_url', 95)->nullable();
            $table->timestamps();
            $table->index('tipo_legislacao_id', 'fk_tipo_legislacoes_idx');
            $table->index('user_id', 'fk_usuario_legislacao_idx');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('legislacoes');
    }
}
