<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.7.0)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateRepresentanteTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('representante', function (Blueprint $table) {
            $table->increments('id');
            $table->unsignedInteger('user_id');
            $table->string('razao', 255)->default('');
            $table->string('cnpj', 255)->default('');
            $table->string('cep', 255)->nullable();
            $table->unsignedInteger('cidade_id')->nullable();
            $table->string('endereco', 255)->nullable();
            $table->string('bairro', 255)->nullable();
            $table->string('numero', 10)->nullable();
            $table->string('complemento', 255)->nullable();
            $table->string('telefone', 255)->nullable();
            $table->string('email', 255)->nullable();
            $table->integer('creden')->nullable();
            $table->string('creden_img', 255)->nullable();
            $table->string('contratosocial', 255)->nullable();
            $table->string('cartaocnpj', 255)->nullable();
            $table->string('procuracao', 255)->nullable();
            $table->string('motivo_descrendenciamento', 255)->nullable();
            $table->timestamps();
            $table->index('user_id', 'representante_FK');
            
            $table->charset = 'latin1';
            $table->collation = 'latin1_swedish_ci';
        });
        
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('representante');
    }
}
